> # IMU Analysis

An IMU (Inertial Measurement Unit) is a device composed of sensors such as an accelerometer, gyroscope, and often a magnetometer, used to measure the motion and orientation of an object in space. The accelerometer records linear acceleration, the gyroscope measures angular velocity, and the magnetometer provides magnetic field information to stabilize the yaw angle. By fusing these signals using algorithms like Kalman or Madgwick filters, the IMU can accurately estimate the object’s orientation and motion, making it essential in biomechanics, robotics, and gait analysis.  

| IMU Field | Meaning | Application |
|---|---|---|
| PacketCounter | Sequential counter for transmitted packets | Detect missing samples and verify data order |
| Acc_X | Acceleration along sensor X axis | Linear motion analysis |
| Acc_Y | Acceleration along sensor Y axis | Linear motion analysis |
| Acc_Z | Acceleration along sensor Z axis | Linear motion analysis |
| FreeAcc_E | Linear acceleration without gravity in East direction | Motion analysis in global ENU frame |
| FreeAcc_N | Linear acceleration without gravity in North direction | Motion analysis in global ENU frame |
| FreeAcc_U | Linear acceleration without gravity in Up direction | Vertical motion analysis |
| AccHR_X | High‑rate acceleration along X axis | High‑frequency motion dynamics |
| AccHR_Y | High‑rate acceleration along Y axis | High‑frequency motion dynamics |
| AccHR_Z | High‑rate acceleration along Z axis | High‑frequency motion dynamics |
| Gyr_X | Angular velocity around X axis | Segment rotation analysis |
| Gyr_Y | Angular velocity around Y axis | Segment rotation analysis |
| Gyr_Z | Angular velocity around Z axis | Segment rotation analysis |
| GyrHR_X | High‑rate angular velocity around X axis | Detailed rotational dynamics |
| GyrHR_Y | High‑rate angular velocity around Y axis | Detailed rotational dynamics |
| GyrHR_Z | High‑rate angular velocity around Z axis | Detailed rotational dynamics |
| Mag_X | Magnetic field along X axis | Heading estimation |
| Mag_Y | Magnetic field along Y axis | Heading estimation |
| Mag_Z | Magnetic field along Z axis | Heading estimation |
| VelInc_X | Velocity increment along X axis | Velocity estimation |
| VelInc_Y | Velocity increment along Y axis | Velocity estimation |
| VelInc_Z | Velocity increment along Z axis | Velocity estimation |
| OriInc_q0 | Quaternion orientation increment (scalar) | Orientation update |
| OriInc_q1 | Quaternion orientation increment X component | Orientation update |
| OriInc_q2 | Quaternion orientation increment Y component | Orientation update |
| OriInc_q3 | Quaternion orientation increment Z component | Orientation update |
| Pressure | Barometric pressure | Altitude estimation |
| Quat_q0 | Quaternion scalar component | 3D orientation representation |
| Quat_q1 | Quaternion X component | 3D orientation representation |
| Quat_q2 | Quaternion Y component | 3D orientation representation |
| Quat_q3 | Quaternion Z component | 3D orientation representation |
| Roll | Rotation around X axis | Orientation analysis |
| Pitch | Rotation around Y axis | Orientation analysis |
| Yaw | Rotation around Z axis | Heading estimation |
| Mat[i][j] | Elements of rotation matrix | Coordinate transformation |
| Latitude | Geographic latitude | Position tracking |
| Longitude | Geographic longitude | Position tracking |
| Altitude | Height above sea level | Position estimation |
| Vel_E | Velocity toward East | Global motion tracking |
| Vel_N | Velocity toward North | Global motion tracking |
| Vel_U | Velocity toward Up | Vertical motion tracking |
| Temperature | Sensor temperature | Sensor monitoring |
| GyrTemp_X | Gyroscope temperature compensation X | Sensor drift correction |
| GyrTemp_Y | Gyroscope temperature compensation Y | Sensor drift correction |
| GyrTemp_Z | Gyroscope temperature compensation Z | Sensor drift correction |

- > **Persian**

| عنوان داده | معنی | کاربرد |
|---|---|---|
| PacketCounter | شمارنده بسته‌های داده | تشخیص نمونه‌های گم‌شده و بررسی ترتیب داده |
| Acc_X | شتاب در محور X سنسور | تحلیل حرکت خطی |
| Acc_Y | شتاب در محور Y سنسور | تحلیل حرکت خطی |
| Acc_Z | شتاب در محور Z سنسور | تحلیل حرکت خطی |
| FreeAcc_E | شتاب بدون گرانش در راستای شرق | تحلیل حرکت در دستگاه ENU |
| FreeAcc_N | شتاب بدون گرانش در راستای شمال | تحلیل حرکت در دستگاه ENU |
| FreeAcc_U | شتاب بدون گرانش در راستای بالا | تحلیل حرکت عمودی |
| AccHR_X | شتاب نرخ‌بالا در محور X | تحلیل دینامیک سریع حرکت |
| AccHR_Y | شتاب نرخ‌بالا در محور Y | تحلیل دینامیک سریع حرکت |
| AccHR_Z | شتاب نرخ‌بالا در محور Z | تحلیل دینامیک سریع حرکت |
| Gyr_X | سرعت زاویه‌ای حول محور X | تحلیل چرخش سگمنت‌ها |
| Gyr_Y | سرعت زاویه‌ای حول محور Y | تحلیل چرخش سگمنت‌ها |
| Gyr_Z | سرعت زاویه‌ای حول محور Z | تحلیل چرخش سگمنت‌ها |
| GyrHR_X | سرعت زاویه‌ای نرخ‌بالا حول X | تحلیل دقیق چرخش |
| GyrHR_Y | سرعت زاویه‌ای نرخ‌بالا حول Y | تحلیل دقیق چرخش |
| GyrHR_Z | سرعت زاویه‌ای نرخ‌بالا حول Z | تحلیل دقیق چرخش |
| Mag_X | میدان مغناطیسی محور X | تخمین جهت (Heading) |
| Mag_Y | میدان مغناطیسی محور Y | تخمین جهت |
| Mag_Z | میدان مغناطیسی محور Z | تخمین جهت |
| VelInc_X | تغییر سرعت در محور X | تخمین سرعت از داده اینرسی |
| VelInc_Y | تغییر سرعت در محور Y | تخمین سرعت از داده اینرسی |
| VelInc_Z | تغییر سرعت در محور Z | تخمین سرعت از داده اینرسی |
| OriInc_q0 | تغییرات کواترنیون (اسکالر) | به‌روزرسانی جهت‌گیری |
| OriInc_q1 | تغییرات کواترنیون (X) | به‌روزرسانی جهت‌گیری |
| OriInc_q2 | تغییرات کواترنیون (Y) | به‌روزرسانی جهت‌گیری |
| OriInc_q3 | تغییرات کواترنیون (Z) | به‌روزرسانی جهت‌گیری |
| Pressure | فشار هوا | تخمین ارتفاع |
| Quat_q0 | جزء اسکالر کواترنیون | نمایش جهت‌گیری سه‌بعدی |
| Quat_q1 | جزء X کواترنیون | نمایش جهت‌گیری سه‌بعدی |
| Quat_q2 | جزء Y کواترنیون | نمایش جهت‌گیری سه‌بعدی |
| Quat_q3 | جزء Z کواترنیون | نمایش جهت‌گیری سه‌بعدی |
| Roll | چرخش حول محور X | تحلیل Orientation |
| Pitch | چرخش حول محور Y | تحلیل Orientation |
| Yaw | چرخش حول محور Z | تعیین جهت حرکت |
| Mat[i][j] | عضو ماتریس چرخش | تبدیل بین سیستم مختصات‌ها |
| Latitude | عرض جغرافیایی | تعیین موقعیت |
| Longitude | طول جغرافیایی | تعیین موقعیت |
| Altitude | ارتفاع از سطح دریا | تحلیل موقعیت |
| Vel_E | سرعت در راستای شرق | تحلیل حرکت در دستگاه ENU |
| Vel_N | سرعت در راستای شمال | تحلیل حرکت در دستگاه ENU |
| Vel_U | سرعت در راستای بالا | تحلیل حرکت عمودی |
| Temperature | دمای سنسور | پایش وضعیت سنسور |
| GyrTemp_X | جبران دمای ژیروسکوپ محور X | کاهش خطای سنسور |
| GyrTemp_Y | جبران دمای ژیروسکوپ محور Y | کاهش خطای سنسور |
| GyrTemp_Z | جبران دمای ژیروسکوپ محور Z | کاهش خطای سنسور |

In [1]:
# Basic lib
import os # Access to the Windows operating system
import math # math in python
import shutil # copy file to anothe folder
from datetime import datetime # date time lib

# analysis
import numpy as np
import pandas as pd

# Statistik
import scipy.stats as stats

# Plot
import matplotlib.pyplot as plt # Plot Graph
import seaborn as sns # Plot Groph

The file paths are defined at the beginning, and throughout this notebook these paths will be used for `reading` or `saving` data.  
If you want to run the code, make sure to update these two paths according to your own directory structure.

In [2]:
# -------------   PATH   -------------
# Path of Main File
input_path = r"C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)"

# Path of Save File
output_path = r"C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\processed\Kinematic data xsens suit"

## 1. Read One File Of IMU

All IMU files in this project are in **`.txt` format**, containing the data described in the table above.  
First, we will read one of these files as a **sample** and examine what components it consists of.  
EX: MT_01200CEF_010-000_00B4D0BD.txt

* MT_01200CEF: Repetitive section    
* 010-000: Name of the test subject  
* 00B4D0BD: Name of the sensor (the body part where the sensor is attached)

### Sensor Location Codes

| ID        | Location | Name      |
|-----------|----------|-----------|
| 00B4D0C2  | Foot R   | calcn_r   |
| 00B4D0C3  | Shoul L  | humerus_l |
| 00B4D0CD  | F Arm L  | radius_l  |
| 00B4D0BD  | Shoul R  | humerus_r |
| 00B4D0C7  | F Arm R  | radius_r  |
| 00B4D0CE  | Hand R   | hand_r    |
| 00B4D0D1  | U Arm R  | radius_r  |
| 00B4D162  | Hand L   | hand_l    |
| 00B4D0CF  | Stern    | torso     |
| 00B4D0CB  | Head     | head      |
| 00B4D0C8  | U Leg L  | femur_l   |
| 00B4D0CC  | U Arm L  | radius_l  |
| 00B4D0D0  | Foot L   | calcn_l   |
| 00B4D0BE  | L Leg L  | tibia_l   |
| 00B4D0BF  | U Leg R  | femur_r   |
| 00B4D0C5  | Pelvis   | pelvis    |
| 00B4D0C4  | L Leg R  | tibia_r   |
| 00B4D0C0  | Prop 1   | prop_1    |

First read the **first 12 lines**, which contain the **sensor information**, and store them in a **DataFrame**.

In [3]:
# Read 12 row in File

# Name EX: File
file_name = "MT_01200CEF_010-000_00B4D0BD.txt"

# Make Path: Make Path with Exampel File
full_path = os.path.join(input_path, file_name)

#---------------------------------------------
# Make one Empty datafram
first_12_row = pd.DataFrame({"Titel": [None]})

# Enter Data each line in Dataframe
with open(full_path, "r", encoding="utf-8") as f:
    for i in range(12):
        line = f.readline().rstrip("\n")
        first_12_row.loc[i, "Titel"] = line

# --- Clean first_12_row---
# Remove "// " in first of each Row
first_12_row["Titel"] = first_12_row["Titel"].str.replace("// ", "", regex=False)

# Split column to 2 columns by ":" 
first_12_row[["Titel", "Value"]] = first_12_row["Titel"].str.split(":", n=1, expand=True)

# Remove Space in first and end of each String
first_12_row["Titel"] = first_12_row["Titel"].str.strip()
first_12_row["Value"] = first_12_row["Value"].str.strip()

#---------------------------------------------
# Make one Dataframe from Data ( row 12 to end)
df_IMU = pd.read_csv(full_path,
                     skiprows=12,  # row 12 to end
                     sep=r"\t",   # separator= \t: one tab = one column
                     decimal=".")  # Float Number (EX: 14.25)

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\2443521527.py:32: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(full_path,

In [4]:
first_12_row

                  Titel                                              Value
0   General information
1    MT Manager version                                           2022.2.0
2           XDA version  2022.2.0 build 7381 rev 124627 built on 2023-0...
3    Device information
4              DeviceId                                           00B4D0BD
5           ProductCode                                         MTW2-3A7G6
6      Firmware Version                                              4.6.0
7      Hardware Version                                              2.0.0
8       Device settings
9        Filter Profile                                        human(46.1)
10         Option Flags  Orientation Smoother Disabled, Position/Veloci...
11    Coordinate system                                                ENU

In [5]:
df_IMU

,PacketCounter,SampleTimeFine,Year,Month,Day,Second,UTC_Nano,UTC_Year,UTC_Month,UTC_Day,...,Latitude,Longitude,Altitude,Vel_E,Vel_N,Vel_U,Temperature,GyrTemp_X,GyrTemp_Y,GyrTemp_Z
0,6950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1,6951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2,6952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
3,6953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,6954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9497,16447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
9498,16448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
9499,16449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
9500,16450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
9501,16451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

## 2. Read all data together

In the `input_path` folder, we read the **names of all `.txt` files**, and then load them into a **single DataFrame**.   
There are **587 files with the `.txt` format** and **63 files with the `.mtb` format**.

In [7]:
# Read Name Of All file
os.makedirs(input_path, exist_ok=True)

# All data drom .txt
file_names_txt = [f for f in os.listdir(input_path) if f.endswith(".txt")]

# All data drom .mtb
file_names_mtb = [f for f in os.listdir(input_path) if f.endswith(".mtb")]

print(f"Count .txt: {len(file_names_txt)} files\nCount .mtb: {len(file_names_mtb)} files")

Count .txt: 587 files
Count .mtb: 63 files

We convert the `file_names_txt` list into a **DataFrame** and create two columns named **Name_User** and **ID**.  

| Field      | Description                                  |
|------------|----------------------------------------------|
| Main_Name  | Original file name                           |
| Name_User  | Name of the person on whom the test was performed |
| ID         | Sensor location                              |

In [8]:
# Make one DataFrame from file_names_txt
df_txt = pd.DataFrame(file_names_txt.copy(), columns=["Main_Name"])

# Print Information about Files
print(f"sampel name of file is : {df_txt["Main_Name"].iloc[0]}")
print(f"0:11 Charechte is : {df_txt["Main_Name"].str[0:11].unique().tolist()}")


print(f"12:19 Charechte is : have {len(df_txt["Main_Name"].str[12:19].unique())} Uniq Caherchter")
print(f"20: Charechte is : have {len(df_txt["Main_Name"].str[20:].unique())} Uniq Caherchter")


# make 2 columns "Name_User" and "ID"
df_txt.insert(loc=1, value=df_txt["Main_Name"].str[12:19], column="Name_User")
df_txt.insert(loc=2, value=df_txt["Main_Name"].str[20:28], column="ID")

df_txt

sampel name of file is : MT_01200CEF_010-000_00B4D0BD.txt
0:11 Charechte is : ['MT_01200CEF']
12:19 Charechte is : have 38 Uniq Caherchter
20: Charechte is : have 18 Uniq Caherchter

                            Main_Name Name_User        ID
0    MT_01200CEF_010-000_00B4D0BD.txt   010-000  00B4D0BD
1    MT_01200CEF_010-000_00B4D0BF.txt   010-000  00B4D0BF
2    MT_01200CEF_010-000_00B4D0C2.txt   010-000  00B4D0C2
3    MT_01200CEF_010-000_00B4D0C3.txt   010-000  00B4D0C3
4    MT_01200CEF_010-000_00B4D0C4.txt   010-000  00B4D0C4
..                                ...       ...       ...
582  MT_01200CEF_048-000_00B4D0CE.txt   048-000  00B4D0CE
583  MT_01200CEF_048-000_00B4D0CF.txt   048-000  00B4D0CF
584  MT_01200CEF_048-000_00B4D0D0.txt   048-000  00B4D0D0
585  MT_01200CEF_048-000_00B4D0D1.txt   048-000  00B4D0D1
586  MT_01200CEF_048-000_00B4D162.txt   048-000  00B4D162

[587 rows x 3 columns]

We have an Excel file named **map_sensor** with the **(.xlsx)** format that contains …

| Field     | Description                                      |
|-----------|--------------------------------------------------|
| ID        | Sensor location                                  |
| Location  | Physical location of the sensor on the body      |
| Name      | The name recognized by the OpenSim software      |

In this dataframe, the names that the OpenSim software uses to recognize the sensors are present.  
Now we merge these names into the **df_txt** dataframe.

With this approach, we get a complete DataFrame containing information from **every file**.  
Therefore, we can **filter by the person's name** to access the files that belong to that person, and then use a **for loop** to read all files for each person.

Additionally, we can determine:
- which **sensor** the file corresponds to,
- the **sensor position/body segment** (location),
- and the **file naming convention** used by the **OpenSim software**.

In [ ]:
# Path of Maping file
PATH_MAP_SENSOR = f"{input_path}\\map_sensor.xlsx"
# Read File that is maping file
MAP_SENSOR = pd.read_excel(PATH_MAP_SENSOR, sheet_name="Tabelle1")

# Merge df_txt and MAP_SENSOR and make tow columns "Location" and "Name"
# Name is name of opensim app
INFORMATION_TXT_FILE = pd.merge(df_txt,
                                MAP_SENSOR,
                                left_on="ID",
                                right_on="ID",
                                how="left")

In [18]:
INFORMATION_TXT_FILE

                            Main_Name Name_User        ID Location       Name
0    MT_01200CEF_010-000_00B4D0BD.txt   010-000  00B4D0BD  Shoul R  scapula_r
1    MT_01200CEF_010-000_00B4D0BF.txt   010-000  00B4D0BF  U Leg R    femur_r
2    MT_01200CEF_010-000_00B4D0C2.txt   010-000  00B4D0C2   Foot R    calcn_r
3    MT_01200CEF_010-000_00B4D0C3.txt   010-000  00B4D0C3  Shoul L  scapula_l
4    MT_01200CEF_010-000_00B4D0C4.txt   010-000  00B4D0C4  L Leg R    tibia_r
..                                ...       ...       ...      ...        ...
582  MT_01200CEF_048-000_00B4D0CE.txt   048-000  00B4D0CE   Hand R     hand_r
583  MT_01200CEF_048-000_00B4D0CF.txt   048-000  00B4D0CF    Stern      torso
584  MT_01200CEF_048-000_00B4D0D0.txt   048-000  00B4D0D0  Foot L     calcn_l
585  MT_01200CEF_048-000_00B4D0D1.txt   048-000  00B4D0D1  U Arm R  humerus_r
586  MT_01200CEF_048-000_00B4D162.txt   048-000  00B4D162   Hand L     hand_l

[587 rows x 5 columns]

By filtering based on `Name_User` and reading all files related to that person, we can build the **OpenSim DataFrame**.
From each file, we need the following columns:

- `time`  
- `sensor_name_q0`  
- `sensor_name_q1`  
- `sensor_name_q2`  
- `sensor_name_q3`  

These columns must appear **side by side in this exact format**.  
The **order of sensors** is not important, but the **order of data for each sensor** must remain consistent.

In [15]:
INFORMATION_TXT_FILE["Name_User"].unique()

array(['010-000', '011-000', '012-000', '013-000', '014-000', '015-000',
       '016-000', '017-000', '018-000', '019-000', '020-000', '021-000',
       '022-000', '023-000', '024-000', '025-000', '026-000', '027-000',
       '028-000', '029-000', '030-000', '031-000', '032-000', '033-000',
       '034-000', '035-000', '037-000', '038-000', '039-000', '040-000',
       '041-000', '042-000', '043-000', '044-000', '045-000', '046-000',
       '047-000', '048-000'], dtype=object)

In [19]:
# list of User
LIST_OF_USER = INFORMATION_TXT_FILE["Name_User"].unique()

# We create a **DataFrame** in which the required columns will be stored after reading each `.txt` file.
for i in LIST_OF_USER:
    df_all_data_txt = pd.DataFrame({"time":[]})
    MASK = INFORMATION_TXT_FILE[INFORMATION_TXT_FILE["Name_User"].eq(i)]
    for j in range(len(MASK)):
        name_of_sensor_for_opensim = MASK["Name"].iloc[j]
        path_of_file_txt = f"{input_path}\\{MASK["Main_Name"].iloc[j]}"
        print(path_of_file_txt)
        df_IMU = pd.read_csv(path_of_file_txt,
                             skiprows=12,  # row 12 to end
                             sep=r"\t",   # separator= \t: one tab = one column
                             decimal=".")
        df_all_data_txt[[f"{name_of_sensor_for_opensim}_q0", 
                         f"{name_of_sensor_for_opensim}_q1",
                         f"{name_of_sensor_for_opensim}_q2",
                         f"{name_of_sensor_for_opensim}_q3"]] = df_IMU[["Quat_q0","Quat_q1", "Quat_q2","Quat_q3"]]

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_010-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_011-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_012-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_013-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_014-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_015-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_016-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_017-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_018-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_019-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_020-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0BD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0BE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0BF.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0C4.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0C7.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0C8.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0CD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0CE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0D0.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_021-000_00B4D162.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0BD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0BE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0BF.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0C4.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0C7.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0CB.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0CD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0CE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0D0.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D0D1.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_022-000_00B4D162.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0BE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0BF.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0C4.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0C7.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0C8.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0CB.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0CE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0D0.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D0D1.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_023-000_00B4D162.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_024-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_025-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_026-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_027-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0BD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0BE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0BF.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0C4.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0C7.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0C8.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0CD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0CE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0D0.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D0D1.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_028-000_00B4D162.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_029-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_030-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_031-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_032-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0CB.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_033-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0BD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0BE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0BF.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0C0.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0C3.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0C4.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0C5.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0C8.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0CB.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0CC.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0CD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0CF.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0D0.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D0D1.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_034-000_00B4D162.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0C0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_035-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0C0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_037-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0C0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_038-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_039-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_040-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_041-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_042-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0BD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0BE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0BF.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0C0.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0C2.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0C3.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0C5.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0C7.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0C8.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0CB.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0CC.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0CD.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0CE.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0D0.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D0D1.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_043-000_00B4D162.txt
C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,
C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0C0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_044-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0C0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_045-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0C0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_046-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0C0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_047-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0BD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0BE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0BF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0C0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0C2.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0C3.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0C4.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0C5.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0C7.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0C8.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0CB.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0CC.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0CD.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0CE.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0CF.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0D0.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D0D1.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

C:\Users\abolhassni\Desktop\TU Darmstadt\Term 2\bewegung\Bewegunganalysieren\Bewegung\data\raw\Kinematic data (xsens suit)\MT_01200CEF_048-000_00B4D162.txt

C:\Users\abolhassni\AppData\Local\Temp\ipykernel_17596\1484953293.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_IMU = pd.read_csv(path_of_file_txt,

In [21]:
df_all_data_txt

,time,scapula_r_q0,scapula_r_q1,scapula_r_q2,scapula_r_q3,tibia_l_q0,tibia_l_q1,tibia_l_q2,tibia_l_q3,femur_r_q0,...,calcn_l_q2,calcn_l_q3,humerus_r_q0,humerus_r_q1,humerus_r_q2,humerus_r_q3,hand_l_q0,hand_l_q1,hand_l_q2,hand_l_q3
0,NaN,0.420703,-0.426995,-0.359558,0.715124,-0.034441,-0.749264,0.010683,-0.661289,0.252529,...,-0.986417,0.033587,-0.431146,-0.412848,0.458647,-0.658265,-0.503298,0.529416,-0.664135,0.159170
1,NaN,0.420636,-0.427012,-0.359681,0.715091,-0.034396,-0.749330,0.010613,-0.661218,0.252658,...,-0.986405,0.033593,-0.431193,-0.412842,0.458553,-0.658303,-0.503220,0.529336,-0.664249,0.159206
2,NaN,0.420454,-0.426924,-0.360060,0.715060,-0.034438,-0.749369,0.010594,-0.661171,0.252934,...,-0.986394,0.033584,-0.431224,-0.412942,0.458408,-0.658321,-0.503216,0.529197,-0.664363,0.159203
3,NaN,0.420568,-0.426778,-0.360325,0.714947,-0.034578,-0.749355,0.010651,-0.661179,0.253116,...,-0.986379,0.033609,-0.431236,-0.412975,0.458287,-0.658377,-0.503299,0.529056,-0.664428,0.159137
4,NaN,0.420743,-0.426676,-0.360382,0.714876,-0.034720,-0.749323,0.010741,-0.661207,0.253362,...,-0.986368,0.033603,-0.431423,-0.412752,0.458504,-0.658243,-0.503406,0.528861,-0.664498,0.159158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17526,NaN,-0.439462,-0.025855,0.080096,-0.894309,0.079097,0.631487,-0.100686,0.764742,-0.179042,...,0.995086,-0.067399,0.326802,0.684312,-0.085136,0.646273,0.824411,-0.029192,0.564441,-0.030013
17527,NaN,-0.437243,-0.046092,0.071173,-0.895337,0.079320,0.629929,-0.097293,0.766441,-0.174396,...,0.995090,-0.067386,0.318552,0.693452,-0.078785,0.641437,0.813369,-0.028345,0.580121,-0.032978
17528,NaN,-0.436735,-0.064104,0.066022,-0.894871,0.077701,0.628610,-0.092293,0.768306,-0.171534,...,0.995094,-0.067388,0.310356,0.701461,-0.073208,0.637395,0.802423,-0.025742,0.594892,-0.039469
17529,NaN,-0.437425,-0.081236,0.060828,-0.893510,0.077078,0.627345,-0.089355,0.769749,-0.168459,...,0.995101,-0.067384,0.304933,0.706920,-0.069954,0.634339,0.792373,-0.022567,0.607700,-0.048334
17530,NaN,-0.438518,-0.097235,0.056273,-0.891673,0.075957,0.625969,-0.085445,0.771423,-0.165603,...,0.995105,-0.067385,0.302050,0.711468,-0.068557,0.630777,0.783158,-0.022632,0.618941,-0.055353

In [23]:
(df_all_data_txt.columns)

Index(['time', 'scapula_r_q0', 'scapula_r_q1', 'scapula_r_q2', 'scapula_r_q3',
       'tibia_l_q0', 'tibia_l_q1', 'tibia_l_q2', 'tibia_l_q3', 'femur_r_q0',
       'femur_r_q1', 'femur_r_q2', 'femur_r_q3', 'prop_1_q0', 'prop_1_q1',
       'prop_1_q2', 'prop_1_q3', 'calcn_r_q0', 'calcn_r_q1', 'calcn_r_q2',
       'calcn_r_q3', 'scapula_l_q0', 'scapula_l_q1', 'scapula_l_q2',
       'scapula_l_q3', 'tibia_r_q0', 'tibia_r_q1', 'tibia_r_q2', 'tibia_r_q3',
       'pelvis_q0', 'pelvis_q1', 'pelvis_q2', 'pelvis_q3', 'radius_r_q0',
       'radius_r_q1', 'radius_r_q2', 'radius_r_q3', 'femur_l_q0', 'femur_l_q1',
       'femur_l_q2', 'femur_l_q3', 'head_q0', 'head_q1', 'head_q2', 'head_q3',
       'humerus_l_q0', 'humerus_l_q1', 'humerus_l_q2', 'humerus_l_q3',
       'radius_l_q0', 'radius_l_q1', 'radius_l_q2', 'radius_l_q3', 'hand_r_q0',
       'hand_r_q1', 'hand_r_q2', 'hand_r_q3', 'torso_q0', 'torso_q1',
       'torso_q2', 'torso_q3', 'calcn_l_q0', 'calcn_l_q1', 'calcn_l_q2',
       'calcn_l_q3', 'humerus_r_q0', 'humerus_r_q1', 'humerus_r_q2',
       'humerus_r_q3', 'hand_l_q0', 'hand_l_q1', 'hand_l_q2', 'hand_l_q3'],
      dtype='object')

In [ ]:
df_IMU = pd.read_csv(full_path,
                     skiprows=12,  # row 12 to end
                     sep=r"\t",   # separator= \t: one tab = one column
                     decimal=".")

In [132]:
INFORMATION_TXT_FILE[INFORMATION_TXT_FILE["Name_User"].eq("013-000")]

                           Main_Name Name_User        ID Location       Name
15  MT_01200CEF_013-000_00B4D0BD.txt   013-000  00B4D0BD  Shoul R  humerus_r
16  MT_01200CEF_013-000_00B4D0BF.txt   013-000  00B4D0BF  U Leg R    femur_r
17  MT_01200CEF_013-000_00B4D0C2.txt   013-000  00B4D0C2   Foot R    calcn_r
18  MT_01200CEF_013-000_00B4D0C3.txt   013-000  00B4D0C3  Shoul L  humerus_l
19  MT_01200CEF_013-000_00B4D0C4.txt   013-000  00B4D0C4  L Leg R    tibia_r
20  MT_01200CEF_013-000_00B4D0C5.txt   013-000  00B4D0C5   Pelvis     pelvis
21  MT_01200CEF_013-000_00B4D0C7.txt   013-000  00B4D0C7  F Arm R   radius_r
22  MT_01200CEF_013-000_00B4D0CB.txt   013-000  00B4D0CB     Head       head
23  MT_01200CEF_013-000_00B4D0CC.txt   013-000  00B4D0CC  U Arm L   radius_l
24  MT_01200CEF_013-000_00B4D0CD.txt   013-000  00B4D0CD  F Arm L   radius_l
25  MT_01200CEF_013-000_00B4D0CE.txt   013-000  00B4D0CE   Hand R     hand_r
26  MT_01200CEF_013-000_00B4D0CF.txt   013-000  00B4D0CF    Stern      torso